name: Publish to PyPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.0

    - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
            version: 1.7.1

    - name: Install dependencies
      run: poetry install --no-root

    - name: Configure PyPI
      run: poetry config pypi-token.pypi ${{secrets.PYPI_API_TOKEN}}

    - name: Publish to PyPI
      run: poetry publish --build
